### PR TITLE
libti*: use APT addons for linux builds

### PR DESCRIPTION
**Pull request by adriweb**
... instead of manual apt-get invocations.

This was actually from a patch of mine here https://github.com/debrouxl/tilibs/commit/c5eaf5d291962c90dea74e8619f42b9ececa3370 that was committed in the other branch

### CODE REVIEW

**Comment by adriweb** [comment]
Since travis also supports such syntax for macOS via brew (that feature is just a [few weeks old](https://github.com/travis-ci/travis-build/pull/1467)), I'll probably make another PR for that soon.

**Comment by debrouxl** [comment]
Thanks for the PR.
Yeah, your suggestion had been implemented for a while on the experimental2 branch, but I noticed I forgot to indicate in my commit message that you made the suggestion, so either I had to rewrite the commit anyway, or better, I could integrate a PR of yours to provide even more explicit attribution :)

**Comment by debrouxl** [comment]
Merges are better done using "Comment" than "Close and comment".

**Comment by adriweb** [comment]
> Since travis also supports such syntax for macOS via brew (that feature is just a [few weeks old](https://github.com/travis-ci/travis-build/pull/1467)), I'll probably make another PR for that soon.
> 
> Edit: that would have worked nicely, but the fact that we need to do `brew link --force gettext libarchive` defeats the point :( Oh well.

Now that we'll more or less have to get rid of the forced brew link (it started not working on libarchive, it may one day not work on gettext... we'll see) and add manual pkg-config paths (for libarchive) and use some "hardcoded" (but still auto-updated/versioned by brew via symlinks) paths to /usr/local/opt/xxxx (for libiconv, gettext), I'll try to see if I can have a modified travis file for that.

**Pull request merged**
