### PR TITLE
Fix clock and version check for 89t

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by debrouxl** [comment]
Despite barely losing data, I still haven't fully recovered my libti*/gfm/tilp build setup from before I dropped my computer on the floor and damaged the HDD, a year ago.

In December 2016, after your report and before this PR, I made a commit on the experimental branch, which supposedly fixes clock handling as well. I probably never tested it correctly.

**Comment by uyjulian** [comment]
This commit should work correctly for me.

**Comment by debrouxl** [comment]
In the last hunk of your commit, you simplified the code. Did that part fail to work before you changed it ?

I did consider getting an SSD to replace the damaged HDD, precisely because of the higher robustness against severe mechanical shocks (well, it was the first time it occurred to me or family in two decades of personal + work laptop usage, but still)... but the TBW metrics of SSDs remain lackluster, and most of all, a higher-end terabyte-class SSD cost at the time, and still costs, more than 500€ at the computer shop close to my work place - which doesn't have the suitable models in stock for immediate buy...
I started doing ~weekly backups of this computer, though :)

**Comment by uyjulian** [comment]
Yes, it failed to work for me. IIRC there was less data in the payload than what was originally read, so I fixed that.

**Comment by debrouxl** [comment]
It's odd that retrieving these attributes failed for you, because they worked (and still work) for me on the 89T HW4 running AMS 3.10 :(
When fed with a slightly edited excerpt from ~/.ticables/ticables-dusb.pkt, here's what libticalcs' DUSB dissector, for which test_ticalcs_2 provides an interactive terminal-based front-end, has to say:
```
Your choice: 36

Enter calc model (usually 13, 14, 18-21): 13
Enter raw DUSB packet as hex string of up to 4 * max raw packet size (non-hex characters ignored; CTRL+D to end):
00000020 (04) 
        0000001a {0008}
                00 04 00 1D 00 00 01 01 00 2D 00 00 
                01 01 00 0A 00 00 01 01 00 23 00 00 
                01 01 

00000020 (04)                                                   | PC>TI: Virtual Packet Data Final
        0000001A {0008}                                         | CMD: Parameter Data
                00 04 00 1D 00 00 01 01 00 2D 00 00 01 01 00 0A 
                00 00 01 01 00 23 00 00 01 01 
Received 4 (4) parameter values:
        001D (Bits per pixel): OK, size 0001
                01 
        002D (Battery level): OK, size 0001
                01 
        000A (OS mode): OK, size 0001
                01 
        0023 (Classic clock supported): OK, size 0001
                01 
Dissection successful
```

There's another bug in calc_89t.c::get_version() anyway, namely the failure to retrieve the OS version, which cascades to a failure to get/set the clock through the TILP GUI... so I'll fix it at the same time.

**Comment by uyjulian** [comment]
I also have AMS 3.10. Maybe there have been some changes to the source code since I made the fix?
You might have a better solution than I did.

This fix is a "works for me" lazy fix, so I didn't bother to look into the problem once it worked for me.

**Comment by debrouxl** [comment]
Nope: I had barely worked on the source code since before you made your fix. My earlier fix on the experimental branch partially overlaps with yours, but I was curious about the hard-coding of INFOS_BPP and INFOS_CLOCK_SUPPORT and the removal of INFO_BATTERY and INFO_RUN_LEVEL.

**Comment by uyjulian** [comment]
I hard-coded/removed some stuff because, apparently, there was less data sent through USB than what the code was attempting to read. Any commit before c05d75c70ca12406ee91b376199d6937657f8d7f  works fine for me.

**Comment by debrouxl** [comment]
Yeah, there was one size issue, which you found and fixed, and I reproduced on my side. Also, I noticed what seems to be an old copy-paste error, from before my time as the maintainer...

I've just pushed a modified version of our changes onto the "experimental2" branch. Could you test it on your side ? Tonight, my main computer refuses to communicate with the 89T, even after rebooting the 89T, and even though the 84+SE and 83PCE work with the same USB cable on the same port...
TIA.

**Comment by debrouxl** [comment]
I have reordered the commits on the experimental2 branch, fixing the TI-68k ROM dumper unification commit, improving the NSP dissector... and of higher interest to you, performing another fix in get_version(): the ability to get the battery status on the 89T through DUSB was lost a while ago.
I used another computer to test the get_version fixes and the new ROM dumpers: both ROM dumpers usable on the 89T work and produce the same result. Testing the Fargo II dumper for the 92 is going to be less fun...

**Comment by uyjulian** [comment]
"Get calc info" works correctly now.

However, setting the clock is still broken, even on your "experimental2" branch.

**Comment by debrouxl** [comment]
So it is...
The main reason for that is the mis-nesting of the main (outer) else {} block in calc_89t.c::get_clock(). It should be inside if (params[0]->ok && params[0]->size == 1) { }, instead of being at the same level.
After fixing that, the expected "Found valid classic clock" trace is displayed, and the clock information looks saner in test_ticalcs_2. It's still incorrect nevertheless: when the calculator is manually set to today's date, libticalcs' output indicates April 2nd, 2018, and when the clock is set to today on the computer, the calculator thinks it's configured for March 3rd, 2018...
A 84+SE doesn't have such an offset, AFAICS, even though the code looks pretty much the same.

From TILP, both getting the clock information and synchronizing the clock are broken. In the former case, the UI contains invalid values, and in the latter case, the calculator barfs an "invalid parameter" error. Fixing that is a task for later...

**Comment by uyjulian** [comment]
It works correctly with latest changes in experimental2 branch.
I'm closing this issue

**Comment by debrouxl** [comment]
Thanks for the report, patch and tests :)

**Pull request closed without merging**
